# Generated by Django 6.1 on 2026-09-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
