# Generated by Django 6.1 on 2026-08-28 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_range', models.CharField(help_text='e.g. 8-12, 10-12', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('group', 'Group'), ('oneonone', 'One-on-One')], max_length=20)),
                ('monthly_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('noproof', 'No proof uploaded'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='noproof', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrolments', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proofs/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='enrolment.enrolment')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=1)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_lines', to='enrolment.enrolment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrolment.subject')),
            ],
            options={
                'unique_together': {('enrolment', 'subject')},
            },
        ),
    ]
