# Generated by Django 6.1 on 2026-09-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0002_seed_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='registration_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
