# Generated by Django 6.1 on 2026-10-02 12:09

import django.db.models.deletion
import enrolment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0003_enrolment_registration_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='late_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LearnerBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('optedout', 'Opted out'), ('disabled', 'Disabled (unpaid)')], default='active', max_length=20)),
                ('late_fee_owed', models.PositiveIntegerField(default=0)),
                ('optout_token', models.CharField(default=enrolment.models.generate_optout_token, max_length=64, unique=True)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_for', models.DateField(blank=True, null=True)),
                ('late_fee_applied_for', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
